### ISSUE TITLE
Clarify is SVM DR is supported with FSX

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-replication#5]
Page: [Set up data replication](https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html)

On this page there are details for using SnapMirror with FSX under this section:
`Requirements specific to Amazon FSx for ONTAP`

Can a note be added here to clarify is using FSx as a SVM DR destination is supported?

**Comment by netapp-bcammett** [comment]
Hi Mike,

Data replication through Cloud Manager is at the volume level. Cloud Manager doesn't support SVM DR for any type of working environment.
